/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra.view;

import hr.algebra.model.User;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.JMenuItem;
import javax.swing.KeyStroke;

/**
 *
 * @author Karla
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuNav = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuNav.setText("Navigation");
        jMenuBar1.add(menuNav);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuNav;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
    
    public void login(final User user){
        configurePanels(user);
    }
    
    private void configurePanels(final User user){
        //final var menuItemLoggedIn = new JMenu
                
        if (user.roleId == 1) {
            tabMain.add("EditArticle", new EditArticlesPanel());
            addMenuItem("EditArticle", KeyEvent.VK_1, 0);
            
            tabMain.add("UploadArticle", new UploadArticlesPanel());
            addMenuItem("UploadArticle", KeyEvent.VK_2, 1);
            
            return;            
        }
                //ctrl + brojevi
        tabMain.add("Shoe", new ShoePanel());
        addMenuItem("Shoe", KeyEvent.VK_1, 0);
        
        tabMain.add("Receipt", new ReceiptPanel());
        addMenuItem("Receipt", KeyEvent.VK_2, 1);
        
        tabMain.add("Customer", new CustomerPanel());
        addMenuItem("Customer", KeyEvent.VK_3, 2);
        
        tabMain.add("Seller", new SellerPanel());
        addMenuItem("Seller", KeyEvent.VK_4, 3);
    }

    private void addMenuItem(final String name, final int keyEvent, final int index) {
        final JMenuItem menuItem = new JMenuItem("Go to " + name);
        menuItem.setAccelerator(KeyStroke.getKeyStroke(keyEvent, InputEvent.CTRL_DOWN_MASK));
        menuItem.addActionListener(e -> tabMain.setSelectedIndex(index));
        menuNav.add(menuItem);
    }

}
